unsigned long LSL(unsigned long Variable_salida,unsigned long Variable_entrada,unsigned long constate_parametro);
unsigned long LSR(unsigned long Variable_salida,unsigned long Variable_entrada,unsigned long constate_parametro);
unsigned long ROR(unsigned long Variable_salida,unsigned long Variable_entrada,unsigned long constate_parametro);
unsigned long ASR(unsigned long Variable_salida,unsigned long Variable_entrada,unsigned long constate_parametro);
unsigned long BIC(unsigned long Variable_salida,unsigned long Variable_entrada);
unsigned long MVN(unsigned long Variable_salida,unsigned long Variable_entrada);
unsigned long RSBS(unsigned long Variable_salida,unsigned long Variable_entrada,unsigned long constate_parametro);
unsigned long REV(unsigned long Variable_salida,unsigned long Variable_entrada);
unsigned long REV16(unsigned long Variable_salida,unsigned long Variable_entrada);
//NOP(long a,long b);
